name: Install ARC
description: 'Install ARC'
inputs:  
  cloudProvider:
    description: 'Cloud Provider'
    type: string
  clusterName:
    description: 'Kubernetes Cluster Name'
    type: string
  regionName:
    description: 'Region where Cluster is deployed'
    type: string
  resourceGroupName:
    description: 'Name of resource group (for Azure only)'
    type: string
  subscriptionId:
    description: 'Subscription ID for your Azure Account'
    type: string

runs:
  using: "composite"
  steps:
  - name: Install GKE Auth Plugin
    if: inputs.cloudProvider == 'gcp'
    uses: "google-github-actions/setup-gcloud@v2"
    with:
      install_components: "gke-gcloud-auth-plugin"
    
  - name: Authenticate to GKE cluster
    if: inputs.cloudProvider == 'gcp'
    uses: google-github-actions/get-gke-credentials@v2
    with:
      cluster_name: ${{ inputs.clusterName }}
      location: ${{ inputs.regionName }}

  - name: Install Helm
    if: inputs.cloudProvider == 'azure'
    uses: azure/setup-helm@v4

  - name: Setup Arc
    shell: bash
    run: |      
      if [ "${{ inputs.cloudProvider }}" == "azure" ]; then
        az account set --subscription ${{ inputs.subscriptionId }}
        az aks command invoke --resource-group "${{ inputs.resourceGroupName }}" --name "${{ inputs.clusterName }}" --file "scripts/setup_arc.sh" --command "export GH_TOKEN="${{ env.GH_TOKEN }}" && chmod ugo+rwx setup_arc.sh && ./setup_arc.sh ${{ inputs.cloudProvider}}"        
      else
        export GH_TOKEN="${{ env.GH_TOKEN }}"
        chmod ugo+rwx scripts/setup_arc.sh
        ./scripts/setup_arc.sh
      fi