name: Build Arc Infra
run-name: build arc infra - ${{ github.event.inputs.CLOUD_PROVIDER }} - ${{ github.event.inputs.ACTION }}
on:
  workflow_dispatch:
    inputs:
      ACTION:
        description: "Action"
        type: choice
        options:
        - plan
        - apply
        - destroy
        - skip
      CLOUD_PROVIDER:
        description: "Cloud Provider"
        type: choice
        options:
        - gcp
        - azure
        - aws
      REGION:
        description: "Region (Location)"
        type: string
        # us-central1-a - gcp
      RUN_INSTALL_ARC:
        description: "Install ARC"
        type: boolean
        default: true

permissions:
  id-token: write
  contents: read
  
jobs:
  build_infra:
    name: Build Infrastructure
    runs-on: [ubuntu-latest]
    environment: ${{ github.event.inputs.CLOUD_PROVIDER }}
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      TERRAFORM_VERSION: 1.7.5
      CLUSTER_NAME: arc-runner-cluster
    steps:
    # Repo checkout
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name }}

    # Cloud-specific Auth Steps
    - name: Setup up Google Cloud Auth
      if: github.event.inputs.CLOUD_PROVIDER == 'gcp'
      env:
        GCP_PROJECT_NUM: 390209572226
        GCP_PROJECT_ID: project-235e2136-7c2e-4409-bad
        SVC_ACCOUNT: terraform-gcp-sa
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/${{ env.GCP_PROJECT_NUM }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "${{ env.SVC_ACCOUNT }}@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
    
    - name: Setup Azure Auth
      if: github.event.inputs.CLOUD_PROVIDER == 'azure'
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
    
    # Terraform Steps
    - name: Setup Terraform
      if: github.event.inputs.ACTION != 'skip'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    
    - name: Export GH Token
      if: github.event.inputs.ACTION != 'skip'
      run: echo "TF_VAR_gh_token=${{ env.GH_TOKEN }}" >> $GITHUB_ENV
        
    - name: Run Terraform
      if: github.event.inputs.ACTION != 'skip'
      env:
        ARM_USE_OIDC: true
        ARM_USE_CLI: false
        ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      run: |
        cd terraform/${{ github.event.inputs.CLOUD_PROVIDER }}
        terraform init
        terraform plan
        if [[ "${{ inputs.ACTION }}" == "apply" ]]; then
          terraform apply -auto-approve
        elif [[ "${{ inputs.ACTION }}" == "destroy" ]]; then
          terraform destroy -auto-approve
        fi  
    
    # Post Terraform Steps - Install/Setup ARC
    - name: Install ARC
      if: github.event.inputs.RUN_INSTALL_ARC == 'true' && github.event.inputs.ACTION != 'destroy'
      uses: kgacandole/github_arc/actions/install_arc@main
      with:
        cloudProvider: ${{ github.event.inputs.CLOUD_PROVIDER }}
        clusterName: ${{ env.CLUSTER_NAME }}
        regionName: ${{ inputs.REGION }}