name: Fix Auth
run-name: Fix Auth

on:
  workflow_dispatch:

jobs:
  fix_auth:
    name: Fix Auth
    runs-on: ubuntu-latest
    environment: 'gcp'
    steps:
    - name: Setup up Google Cloud Auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/${{ vars.GCP_PROJECT_NUM }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "${{ vars.SVC_ACCOUNT }}@${{ vars.GCP_PROJECT_ID }}.iam.gserviceaccount.com"
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Fix bindings
      shell: bash
      run: |
        gcloud iam service-accounts remove-iam-policy-binding terraform-gcp-sa@project-235e2136-7c2e-4409-bad.iam.gserviceaccount.com --role="roles/iam.workloadIdentityUser" --member="principalSet://iam.googleapis.com/projects/390209572226/locations/global/workloadIdentityPools/github-pool/attribute.repository/kgacandole/github_arc"

        gcloud iam service-accounts remove-iam-policy-binding terraform-gcp-sa@project-235e2136-7c2e-4409-bad.iam.gserviceaccount.com --role="roles/iam.serviceAccountTokenCreator" --member="principalSet://iam.googleapis.com/projects/390209572226/locations/global/workloadIdentityPools/github-pool/attribute.repository/kgacandole/github_arc"

        gcloud iam service-accounts add-iam-policy-binding terraform-gcp-sa@project-235e2136-7c2e-4409-bad.iam.gserviceaccount.com --role="roles/iam.workloadIdentityUser" --member="principalSet://iam.googleapis.com/projects/390209572226/locations/global/workloadIdentityPools/github-pool/attribute.repository/kgacdevops/github_arc"

        gcloud iam service-accounts add-iam-policy-binding terraform-gcp-sa@project-235e2136-7c2e-4409-bad.iam.gserviceaccount.com --role="roles/iam.serviceAccountTokenCreator" --member="principalSet://iam.googleapis.com/projects/390209572226/locations/global/workloadIdentityPools/github-pool/attribute.repository/kgacdevops/github_arc"