name: Install ARC
run-name: install arc - ${{ github.event.inputs.CLOUD_PROVIDER }} - ${{ github.event.inputs.REGION }}
on:
  workflow_dispatch:
    inputs:
      CLOUD_PROVIDER:
        description: "Cloud Provider"
        type: choice
        options:
        - azure
        - gcp
        - aws
      REGION:
        description: "Region"
        type: string

jobs:
  install_arc:
    permissions:
      id-token: write
      contents: write
      repository-projects: write
      actions: write
    uses: kgacandole/cicd_arc/.github/workflows/install_arc.yml@main
    secrets: inherit
    with:
      CLOUD_PROVIDER: ${{ github.event.inputs.CLOUD_PROVIDER }}
      REGION: ${{ github.event.inputs.REGION }}