name: Install Prereqs
run-name: install prereqs - ${{ github.event.inputs.CLOUD_PROVIDER }}

on:
  workflow_dispatch:
    inputs:
      CLOUD_PROVIDER:
        description: "Action"
        type: choice
        options:
        - azure
        - gcp
        - aws
      REGION:
        description: "Region"
        type: string

jobs:
  install_prereqs:
    permissions:
      id-token: write
      contents: write
      repository-projects: write
      actions: write
    uses: kgacdevops/cicd_arc/.github/workflows/install_pre_req.yml@main
    secrets: inherit
    with:
      CLOUD_PROVIDER: ${{ github.event.inputs.CLOUD_PROVIDER }}
      REGION: ${{ github.event.inputs.REGION }}
