name: Test Workflow
run-name: Test workflow
on:
  workflow_dispatch

jobs:
  init:
    name: Initialize
    runs-on: [ubuntu-latest]
    steps:
    - name: Test Runner
      run: echo "Hello world!"
    
    - name: Save Secrets
      run: |
        echo "${{ secrets.GH_APP_ID }}" > gh_keys.txt
        echo "${{ secrets.GH_APP_PRIVATE_KEY }}" >> gh_keys.txt
        echo "${{ secrets.GH_INSTALLATION_ID }}" >> gh_keys.txt

    - name: Upload Secrets
      uses: actions/upload-artifact@v4
      with:
        name: gh-keys
        path: gh_keys.txt